name: marine_star
description: This is an app for marine life captain & sailors.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  modal_bottom_sheet: ^1.0.0+1
  webview_flutter: ^1.0.7
  url_launcher: ^5.7.10
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Louis George Cafe Bold
      fonts:
        - asset: assets/fonts/Louis George Cafe Bold.ttf
          weight: 700
        - asset: assets/fonts/Louis George Cafe.ttf